### ISSUE TITLE
[Notice] personal_access_token

### ISSUE THREAD

**Issue by Eric860730** [ianre657/invisible-hand#4]
在設定personal_access_token時，若設定錯誤，在操作scripts時應該要報這個錯誤
![2](https://user-images.githubusercontent.com/45251297/93660290-cb7d5280-fa7f-11ea-92d5-43fea08791ac.png)

原因是在輸入personal_access_token時沒有把<>拿掉，只要把<>拿掉就可以跑了！

可以把 <> 拔掉避免誤會

**Comment by ianre657** [comment]
@Eric860730  #6  
可以幫我檢查看看有沒有成功改好嗎
